Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 200

Metrics/AbcSize:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 20

Metrics/BlockLength:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 9
