---
accounts:
  - :name: production
  - :name: testing

regions:
  - us-east-1:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1e
  - us-west-1:
    - us-west-1a
    - us-west-1c

ssh_keys:
  - name: prod1
    account: production
  - name: prod2
    account: production
  - name: test-key
    account: testing

buckets:
  - name: testingbucket
    size: 10000000
    account: testing
    region: us-west-1
  - name: productionbucket
    size: 90999000000
    account: production
    region: us-east-1
  - name: productionstate
    size: 12089
    account: production
    region: us-east-1

vpcs:
  - vpc_id: vpc-21121
    name: prod-vpc-1
    state: available
    default: false
    cidr: 192.168.0.0/24
    region: us-east-1
    account: production
  - vpc_id: vpc-21122
    name: test-vpc-1
    state: available
    default: false
    cidr: 192.168.5.0/24
    region: us-west-1
    account: testing

subnets:
  - subnet_id: subnet-444444
    cidr: 192.168.5.0/25
    name: test-subnet-public
    ip_count: 128
    state: avaliable
    az: us-west-1a
    vpc_id: vpc-21122
  - subnet_id: subnet-444445
    cidr: 192.168.5.128/25
    name: test-subnet-private
    ip_count: 128
    state: avaliable
    az: us-west-1c
    vpc_id: vpc-21122
  - subnet_id: subnet-555555
    cidr: 192.168.0.0/26
    name: test-subnet-public
    ip_count: 64
    state: avaliable
    az: us-east-1a
    vpc_id: vpc-21121
  - subnet_id: subnet-555556
    cidr: 192.168.0.64/26
    name: test-subnet-private
    ip_count: 64
    state: avaliable
    az: us-east-1b
    vpc_id: vpc-21121
  - subnet_id: subnet-555557
    cidr: 192.168.0.128/25
    name: test-subnet-private
    ip_count: 128
    state: avaliable
    az: us-east-1d
    vpc_id: vpc-21121

nodes:
  - node_id: i-1111111111
    name: web1
    ip: 192.168.5.2
    public_ip: 8.8.8.8
    size: m1.medium
    ami: ami-12345678
    subnet_id: subnet-444444
    az: us-west-1a
    ssh_key: test-key
    account: testing
  - node_id: i-1111111112
    name: web2
    ip: 192.168.5.3
    public_ip: 8.8.8.4
    size: m1.medium
    ami: ami-12345678
    subnet_id: subnet-444444
    az: us-west-1a
    ssh_key: test-key
    account: testing
  - node_id: i-1111111113
    name: app1
    ip: 192.168.5.201
    public_ip: ""
    size: m1.medium
    ami: ami-12345678
    subnet_id: subnet-444445
    az: us-west-1a
    ssh_key: test-key
    account: testing
